name: Talisman Security Scan

on:
  push:
    branches:
      - '**'  # This will run on pushes to any branch
  pull_request:
    branches:
      - '**'  # This will run on pull requests to any branch

jobs:
  talisman:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Talisman
      run: |
        curl -sL https://github.com/thoughtworks/talisman/releases/latest/download/talisman_linux_amd64 -o talisman
        chmod +x talisman
        sudo mv talisman /usr/local/bin/

    - name: Run Talisman
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          git checkout -b talisman-scan
          git reset --soft ${{ github.event.pull_request.base.sha }}
          talisman --scan
        else
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs talisman --scan
        fi
      env:
        TALISMAN_HOME: ${{ github.workspace }}

    - name: Upload Talisman Report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: talisman-report
        path: talisman_report/talisman_reports/data
