name: Talisman Security Scan

on:
  pull_request:
    branches:
      - '**'  # This will run on pull requests to any branch

jobs:
  talisman:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Talisman
      run: |
        curl -sL https://github.com/thoughtworks/talisman/releases/latest/download/talisman_linux_amd64 -o talisman
        chmod +x talisman
        sudo mv talisman /usr/local/bin/

    - name: Run Talisman
      id: run_talisman
      continue-on-error: true
      run: |
        git checkout -b talisman-scan
        git reset --soft ${{ github.event.pull_request.base.sha }}
        talisman --scan

    - name: Check Talisman Result
      run: |
        if [ "${{ steps.run_talisman.outcome }}" == "failure" ]; then
          echo "::warning::Talisman found potential security issues. Please check the scan results."
        else
          echo "Talisman scan passed successfully."
        fi

    - name: Upload Talisman Report
      if: steps.run_talisman.outcome == 'failure'
      uses: actions/upload-artifact@v3
      with:
        name: talisman-report
        path: talisman_report/talisman_reports/data

