name: Talisman Security Scan

on:
  pull_request:
    branches:
      - '**'  # This will run on pull requests to any branch

jobs:
  talisman:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Talisman
      run: |
        curl --silent --location https://github.com/thoughtworks/talisman/releases/latest/download/talisman_linux_amd64 --output /usr/local/bin/talisman
        chmod +x /usr/local/bin/talisman

    - name: Run Talisman
      id: run_talisman
      continue-on-error: true
      run: |
        talisman --scanWithHtml

    - name: Check Talisman Result
      run: |
        if [ "${{ steps.run_talisman.outcome }}" == "failure" ]; then
          echo "::warning::Talisman found potential security issues. Please check the scan results."
          exit 1
        else
          echo "Talisman scan passed successfully."
        fi

    - name: Upload Talisman Report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: talisman-report
        path: talisman_reports/data/report.html
