name: Talisman Security Scan

on:
  pull_request:
    branches:
      - '**'  # This will run on pull requests to any branch

jobs:
  talisman:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Talisman
      run: |
        curl --silent --location https://github.com/thoughtworks/talisman/releases/latest/download/talisman_linux_amd64 --output /usr/local/bin/talisman
        chmod +x /usr/local/bin/talisman

    - name: Run Talisman
      id: run_talisman
      continue-on-error: true
      run: |
        talisman --scanWithHtml > talisman_output.txt 2>&1

    - name: Process Talisman Result
      run: |
        echo "Talisman Scan Results:"
        cat talisman_output.txt
        
        if grep -q "Talisman Report" talisman_output.txt; then
          echo "::warning::Talisman found potential security issues. Please review the results above."
          echo "TALISMAN_FOUND_ISSUES=true" >> $GITHUB_ENV
        else
          echo "Talisman scan passed successfully."
          echo "TALISMAN_FOUND_ISSUES=false" >> $GITHUB_ENV
        fi

    - name: Upload Talisman Report
      if: env.TALISMAN_FOUND_ISSUES == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: talisman-report
        path: talisman_reports/data/report.html

    - name: Summarize Talisman Result
      run: |
        if [ "${{ env.TALISMAN_FOUND_ISSUES }}" == "true" ]; then
          echo "Talisman found potential security issues. Please review the console output and the uploaded HTML report for details."
        else
          echo "Talisman scan completed successfully with no issues found."
        fi
